### ISSUE TITLE
Detecting translocations on same chromosome

### ISSUE THREAD

**Issue by abolia** [zeeev/wham#21]
Hi Zev, 

I am using WHAM to find translocations on my dataset and based on the description specified for WHAM, I see that you can only call a translocation on different chromosomes (basically by looking at the difference in CHROM and chr2 id). Is there a way WHAM can report translocations on the same chromosome? 

Thanks for your help.

Ashini.

**Comment by zeeev** [comment]
The breakpoints will be reported in the VCF file, however they might not have the "TRA" tag after classification.  How big of intra-chomosomal events are you looking at?  I might ignore the classification and look for large SV calls.  If you have a set of known intra-chomosomal translocation you could create your own classifier dataset.

--Zev

**Comment by abolia** [comment]
Thanks Zev. This helps. I will look for the large SV calls. 

Thanks, 
Ashini
