### ISSUE TITLE
-m flag vs NC from info field

### ISSUE THREAD

**Issue by abolia** [zeeev/wham#24]
Hi Zev, 

Can you please help me understand how are the "-m" flag and "NC" related. To my knowledge, both relate to the # of soft clipped required at the breakpoint. I am using -m flag (minimum number of soft-clips supporting START) as 15 while running WHAM but I see that most of my calls still have NC < 15. It shouldn't actually report any SV that has soft clips collapsed into the consensus that are less than 15. Can you please clarify this one for me. 

Thanks for your help.

Ashini

**Comment by zeeev** [comment]
@abolia Thank you for pointing out the bug.  I've fixed it. Let me know if you have any more problems.

**Comment by abolia** [comment]
Great. 

Thanks,
Ashini
