### ISSUE TITLE
No genotype done in the current version WHAM-Graphening

### ISSUE THREAD

**Issue by sehrrot** [zeeev/wham#34]
Hi 

I recently updated the wham-graphening for the version: v1.7.0-199-g6106. I ran the genotyping for merged VCF (three samples in one VCF) and genotyping was not done for some of predictions, like ./. 
others have 0/1 or 1/1.

The previous version v1.7.0-184-gd30f was okay for the same input.

**Comment by zeeev** [comment]
@sehrrot Can you share a few examples?  I've been tweaking the genotyping methods.

**Comment by sehrrot** [comment]
Here are commands for both versions and one line of VCFs. Thanks

**WHAM-GRAPHENING:v1.7.0-199-g6106**

cmd:
~/wham/bin/WHAM-GRAPHENING -m 30 -b ./wham_test/wham.merge.test.vcf -a /home/ec2-user/reference/b37/human_g1k_v37.fasta -e MT -f sample1.bam,sample2.sample3.bam,sample4.bam 2> ./err.wham.step2.test.txt > ./wham_11993/wham.final.test.vcf


**VCF**
CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample1        sample2        sample3        sample4
1       884042  WG:DUP:WG:DUP:6ae33f9a  C       <DUP>   .       .       SVTYPE=DUP;SVLEN=68;ID=WG:DUP:6ae33f9a;SUPPORT=31,32;MERGED=0;REFINED=0;END=884110;POS=884042,884110;FIVE=884042,884042,884042,884042;THREE=884110,884110,884110,884110;LID=sample1,sample2,sample3,sample4;RID=sample1,sample2,sample3,sample4;CIPOS=-10,10;CIEND=-10,10;COLLAPSED=4   GT:GL:AS:RS     ./.:.:0:0       ./.:.:0:0       ./.:.:0:0       ./.:.:0:0

**source=WHAM-GRAPHENING:v1.7.0-184-gd30f**

cmd:
~/wham-v1.7.0/bin/WHAM-GRAPHENING -m 30 -b ./wham_test/wham.merge.test.vcf -a /home/ec2-user/reference/b37/human_g1k_v37.fasta -e MT -f sample1.bam,sample2.sample3.bam,sample4.bam 2> ./err.wham.step2.test.txt > ./wham_11993/wham.final.test.vcf

**VCF**
CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample1        sample2        sample3        sample4
1       884042  WG:DUP:0e97c65e,3beaa0b8,82b86378,89d508ed      C       <DUP>   .       .       SVTYPE=DUP;SVLEN=69;ID=0e97c65e,3beaa0b8,82b86378,89d508ed;SUPPORT=31,31;MERGED=0;REFINED=1;END=884111;POS=884042,884111;FIVE=884042,884042,884042,884042;THREE=884110,884110,884110,884110;LID=sample1,sample2,sample3,sample4;RID=sample1,sample2,sample3,sample4;CIPOS=-10,10;CIEND=-10,10;COLLAPSED=4       GT:GL:AS:RS     0/1:-1393.97,-1103.78,-1343.8:34:43     0/1:-1376.1,-1072.51,-1556.91:34:54     0/1:-714.362,-602.945,-853.346:18:35    1/1:-2584.44,-2079.4,-2062.05:67:29

**Comment by zeeev** [comment]
@sehrrot Thank you.  I'm currently working on improving the genotyping.  I'll keep this in mind.
