### ISSUE TITLE
WHAM taking too long to run

### ISSUE THREAD

**Issue by abolia** [zeeev/wham#36]
Hi Zev, 

Sorry for re-posting this. I posted it on a closed issue so re-posting this. 

"
I am trying to run WHAM for some single end data. But its been more than 10 hours and it still says "**INFO: gathering stats for each bam file**." 
I have already removed this https://github.com/zeeev/wham/blob/master/src/bin/multi-wham-testing.cpp#L622
so it does not throw out error and is still running. Moreover, there are only 84 @SQ tags in the header file and its a pretty small BAM file with about ~ 71000 reads.

Do you think it might be coz its single end data. Please let me know.

Thank you for all your help.
"

Thanks, 
Ashini

**Comment by zeeev** [comment]
WHAM was designed for paired end data.

**Comment by abolia** [comment]
Okay, got you. Thanks.

Ashini
