### ISSUE TITLE
Floating Point Exception

### ISSUE THREAD

**Issue by akkellogg** [zeeev/wham#40]
Hello,

I'm having a problem running WHAM on some smaller BAM files. Every time I try to run it the WHAM.err file returns the following:

INFO: WHAM-BAM will using the following fasta: ../ABL1_cds.fasta
INFO: OpenMP will roughly use 24 threads
INFO: target bams:
 S2.bam
INFO: gathering stats for each bam file.

At which point it exits out and prints "Floating Point Exception" to the terminal.

The reads are aligned with BWA-MEM, and duplicates marked with Picard. Any idea what would be causing this issue? My BAM file is relatively small, could this be causing the problem?

Thanks for your help.

-Ana

**Comment by zeeev** [comment]
@akkellogg Sorry for the late reply, i'm just returning from holiday. What type of data are you working with?  Exome or genome?

**Comment by akkellogg** [comment]
@zeeev We think we pinpointed the problem. We were aligning the reads to a custom reference and we think the issue was with that reference, since aligning to a different reference seems to have solved the problem.
