### ISSUE TITLE
About -e $EXCLUDE 

### ISSUE THREAD

**Issue by xie186** [zeeev/wham#42]
Could you please give me a short description of -e ?

I'm a little bit of confused.
In the help message:
```
  *|-e    -c  <STRING>  Comma sep. list of seqids to keep [false].
```
This means the chrom ID given to -e should be INCLUDEd. But here in the README. you say -e $EXCLUDE. 
Which one is correct? Thanks.

**Comment by zeeev** [comment]
For exclusion use -e and for inclusion use -c.  

e.g.

-e chrMT,chrY

**Comment by xie186** [comment]
Got it. Thanks.
